################################################################################
#                        Environment-specific settings
################################################################################

# Default commands to load modulefiles, etc.
shell_prefix: >-
  shopt -s expand_aliases;

# Default modules
modules:
  hifiasm: "hifiasm"
  gfatools: "gfatools"

################################################################################
#                         Dataset-specific settings
################################################################################

hifi_fastq: "your-hifi-fastq-file"
out_dir: "."
hifiasm_options: ""
