################################################################################
#                        Environment-specific settings
################################################################################

# Default commands to load modulefiles, etc.
shell_prefix: >-
  shopt -s expand_aliases;

# Default modules
modules:
  winnowmap: "winnowmap"
  samtools: "samtools"

################################################################################
#                         Dataset-specific settings
################################################################################

hifi_fastq: "your-hifi-fastq-file"
asm_fasta: "your-assembly-fasta-file"
out_dir: "."
